(define (install-real-package)
  (define (tag x)
    (attach-tag 'real x))
  (put 'add '(real real) +)
  (put 'sub '(real real) -)
  (put 'mul '(real real) *)
  (put 'div '(real real) /)
  (put 'make 'real-scheme-number
       (lambda (x) (tag x)))
  (put 'equ? '(real real) =)
  (put '=zero? '(real)
       (lambda (x) (= x 0)))
  (put 'sine '(real)
       (lambda (x) (sin x)))
  (put 'cosine '(real)
       (lambda (x) (cos x)))
  (put 'square '(real)
       (lambda (x) (square x)))
  (put 'sqrt '(real)
       (lambda (x) (sqrt x)))
  (put 'atan '(real)
       (lambda (x) (atan x)))
  'done)
