(define (install-real-package)
  (define (tag x)
    (attach-tag 'real x))
  (define (real->complex x)
    (make-complex-from-real-imag x 0))
  (put 'add '(real real) +)
  (put 'sub '(real real) -)
  (put 'mul '(real real) *)
  (put 'div '(real real) /)
  (put 'make 'real-scheme-number
       (lambda (x) (tag x)))
  (put 'equ? '(real real) =)
  (put '=zero? '(real)
       (lambda (x) (= x 0)))
  (put 'sine '(real)
       (lambda (x) (sin x)))
  (put 'cosine '(real)
       (lambda (x) (cos x)))
  (put 'square '(real)
       (lambda (x) (square x)))
  (put 'sqrt '(real)
       (lambda (x) (sqrt x)))
  (put 'atan '(real)
       (lambda (x) (atan x)))
  (put 'negate '(real)
       (lambda (x) (- x)))
  (put 'project '(real) (lambda (x) (make-rational-from-real x)))
  (put 'raise '(real) real->complex)
  'done)

(define (make-real-scheme-number n)
  ((get 'make 'real-scheme-number) n))
